obj-$(CONFIG_CAMERA_FPGA_DPHY) += fimc-is-fpga-dphy.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-f62
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-f62/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-f62/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2-f62/sensor
