obj-$(CONFIG_CAMERA_APERTURE_AK7372_OBJ) += fimc-is-aperture-ak7372.o

ccflags-y := -Idrivers/media/platform/exynos/fimc-is2-f62
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-f62/include
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-f62/vendor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-f62/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-f62/sensor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2-f62/sensor/module_framework
